apiVersion: v1
kind: Service
metadata:
  name: eks-demo
  namespace: eks-demo
  annotations:
    # Creates a Network Load Balancer instead of the older Classic one.
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: eks-demo
  ports:
    - port: 80
      targetPort: 8000
